[font]
  size = 9.0
  # normal = { family = "JetBrainsMono Nerd Font", style="Regular" }
[keyboard]
bindings = [


  # ON OSX Press Option + PUS code to input
  # e.g: Option + 2 0 A C = €
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "=", mods = "Control", action = "ResetFontSize" },

  # # https://github.com/zellij-org/zellij/issues/735#issuecomment-1973177193
  # { key = "K",     mods = "Command", chars = "\uE170" },
  # { key = "J",     mods = "Command", chars = "\uE171" },
  # { key = "T",     mods = "Command", chars = "\uE172" },
  # { key = "X",     mods = "Command", chars = "\uE100" },
  { key = "/",     mods = "Control", chars = "\u001F" },

  { key = "Up",     mods = "Control", chars = "\u001b[1;5A" },
  { key = "Down",     mods = "Control", chars = "\u001b[1;5B" },

  # # { key = "j", mods = "Control|Shift", chars = "\uE173" },
  { key = "j", mods = "Command|Shift", chars = "\uE173" },
  { key = "k", mods = "Command|Shift", chars = "\uE174" },

  # tmux
  { key = "t", mods = "Command", chars = "\uE175" },
  # move to next tab
  { key = "k", mods = "Command", chars = "\u0011n" },
  # move to previous tab
  { key = "j", mods = "Command", chars = "\u0011p" },
  { key = "x", mods = "Command", chars = "\uE118" },


  # # NOT working
  # # { key= "Right",    mods= "Control", chars = "\u001b[1;5C" },
  # # { key ="Left",     mods= "Control", chars = "\u001b[1;5D" },

  # # full screen
  # { key = "F11", mods = "Control", action = "ToggleFullscreen" }
]
[window]
  decorations = "buttonless"
  startup_mode = "Maximized"
